package com.alperen.unitercih.utils

import com.alperen.unitercih.db.Department
import com.alperen.unitercih.db.Rule

/**
 * Created by Alperen on 4.11.2021.
 */
object Constants {
    // Rules
    const val RULE_1 = "is_memorize_good"
    const val RULE_2 = "is_human_releations_good"
    const val RULE_3 = "is_arithmetic_good"
    const val RULE_4 = "is_complex_system_good"
    const val RULE_5 = "is_interested_money"
    const val RULE_6 = "is_interested_tech_devices"
    const val RULE_7 = "is_good_drawer"
    const val RULE_8 = "is_likes_books_and_movies"
    const val RULE_9 = "is_good_teacher"
    const val RULE_10 = "is_good_listener"
    const val RULE_11 = "is_interested_crafting"
    const val RULE_12 = "is_likes_learn_brilliant_knowledge"
    const val RULE_13 = "is_hands_dont_vibrate"
    const val RULE_14 = "is_foreign_language_easy"
    const val RULE_15 = "is_interested_medical"
    const val RULE_16 = "is_handle_crisis"
    const val RULE_17 = "is_likes_office"
    const val RULE_18 = "is_good_at_foods"
    const val RULE_19 = "is_wants_goverment_job"
    const val RULE_20 = "is_eligible_for_manager"
    const val RULE_21 = "is_wants_difference"
    const val RULE_22 = "is_emotional_quotient_dominant"
    const val RULE_23 = "is_likes_programming"
    const val RULE_24 = "is_likes_helping"
    const val RULE_25 = "is_likes_work_alone"

    // According question for rule (RULE_1 = QUESTION_1)
    const val QUESTION_1 = "Ezber yeteneğim iyidir"
    const val QUESTION_2 = "İnsan ilişkilerinde iyiyimdir"
    const val QUESTION_3 = "Sayısal yeteneklerime güvenirim"
    const val QUESTION_4 = "Karmaşık sistemler kurabileceğime inanıyorum"
    const val QUESTION_5 = "Para ve parayla ilgili şeylerle ilgilenmekten hoşlanırım"
    const val QUESTION_6 = "Teknolojik cihazlara ilgim var"
    const val QUESTION_7 = "İyi bir çizerim"
    const val QUESTION_8 = "Kitap okumayı, film ve dizi izlemeyi severim"
    const val QUESTION_9 = "Bildiğim bir konuyu diğer insanlara rahatlıkla öğretebiliyorum"
    const val QUESTION_10 = "İyi bir dinleyiciyimdir"
    const val QUESTION_11 = "Yeni bir şeyler oluşturmayı, yapmayı severim"
    const val QUESTION_12 = "Ufkumu açan bilgiler öğrenmek beni mutlu ediyor"
    const val QUESTION_13 = "Ellerim titremez/çok az titrer"
    const val QUESTION_14 = "Yabancı dil benim için bir problem değil"
    const val QUESTION_15 = "Sağlık sektörüne ilgim var"
    const val QUESTION_16 = "Kriz yönetimi yapabilirim"
    const val QUESTION_17 =
        "Bir sahada çalışmak yerine ofiste veya kapalı alanda çalışmayı tercih ederim"
    const val QUESTION_18 =
        "Yemeklerle ilgili bilgimin diğer insanlardan daha iyi olduğunu düşünüyorum"
    const val QUESTION_19 = "Devlet bünyesinde bir iş istiyorum"
    const val QUESTION_20 = "Birçok çalışanın müdürü olmaya uygunum"
    const val QUESTION_21 = "Aynı şeyi defalarca yapmaktan sıkılan, yenilik arayan biriyim"
    const val QUESTION_22 = "Duygusal zekam, mantıksal zekama göre daha ön plandadır"
    const val QUESTION_23 = "Programlamaya ilgim var/seviyorum"
    const val QUESTION_24 = "Zor durumdakilere yardım etmeyi severim"
    const val QUESTION_25 = "Bir ekip yerine tek başıma çalışmayı tercih ederim"

    val CONSTANT_DEPARTMENTS = listOf(
        // Hukuk
        Department(
            id = 0,
            departmentName = "Hukuk",
            isMemoriseGood = true,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = true,
            isLikesWorkAlone = true
        ),

        // Tip
        Department(
            id = 0,
            departmentName = "Tıp",
            isMemoriseGood = true,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = true,
            isForeignLanguageEasy = false,
            isInterestedMedical = true,
            isHandleCrisis = true,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = true,
            isLikesWorkAlone = true
        ),

        // Rehberlik ve Psikolojik Danismanlik
        Department(
            id = 0,
            departmentName = "Rehberlik ve Psikolojik Danışmanlık",
            isMemoriseGood = false,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = true,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = true,
            isLikesWorkAlone = true
        ),

        // Mimarlik
        Department(
            id = 0,
            departmentName = "Mimarlık",
            isMemoriseGood = false,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = true,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = true,
            isLikesWorkAlone = true
        ),

        // İnsaat Muhendisligi
        Department(
            id = 0,
            departmentName = "İnşaat Mühendisliği",
            isMemoriseGood = false,
            isHumanReleationsGood = false,
            isArithmeticGood = true,
            isComplexSystemGood = true,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = true,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = true,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = false,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = true,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = false
        ),

        // Dis Hekimligi
        Department(
            id = 0,
            departmentName = "Diş Hekimliği",
            isMemoriseGood = true,
            isHumanReleationsGood = false,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = true,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = true,
            isForeignLanguageEasy = false,
            isInterestedMedical = true,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Eczacilik
        Department(
            id = 0,
            departmentName = "Eczacılık",
            isMemoriseGood = true,
            isHumanReleationsGood = false,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = true,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = true,
            isWantsDifference = false,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Psikoloji
        Department(
            id = 0,
            departmentName = "Psikoloji",
            isMemoriseGood = true,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = true,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = true,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Hemsirelik
        Department(
            id = 0,
            departmentName = "Hemşirelik",
            isMemoriseGood = false,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = true,
            isForeignLanguageEasy = false,
            isInterestedMedical = true,
            isHandleCrisis = true,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = true,
            isLikesWorkAlone = false
        ),

        // Bilgisayar Muhendisligi
        Department(
            id = 0,
            departmentName = "Bilgisayar Mühendisliği",
            isMemoriseGood = true,
            isHumanReleationsGood = false,
            isArithmeticGood = true,
            isComplexSystemGood = true,
            isInterestedMoney = false,
            isInterestedTechDevices = true,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = true,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = true,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Makine Muhendisligi
        Department(
            id = 0,
            departmentName = "Makine Mühendisliği",
            isMemoriseGood = true,
            isHumanReleationsGood = false,
            isArithmeticGood = true,
            isComplexSystemGood = true,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = true,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = true,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = true,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Isletme
        Department(
            id = 0,
            departmentName = "İşletme",
            isMemoriseGood = false,
            isHumanReleationsGood = true,
            isArithmeticGood = true,
            isComplexSystemGood = false,
            isInterestedMoney = true,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = true,
            isLikesOffice = true,
            isGoodAtFoods = true,
            isWantsGovermentJob = false,
            isEligibleForManager = true,
            isWantsDifference = true,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = false
        ),

        // Elektrik-Elektronik Muhendisligi
        Department(
            id = 0,
            departmentName = "Elektrik-Elektronik Mühendisliği",
            isMemoriseGood = false,
            isHumanReleationsGood = false,
            isArithmeticGood = true,
            isComplexSystemGood = true,
            isInterestedMoney = false,
            isInterestedTechDevices = true,
            isGoodDrawer = true,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = true,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = true,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = true,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Fizyoterapi ve Rehabilitasyon
        Department(
            id = 0,
            departmentName = "Fizyoterapi ve Rehabilitasyon",
            isMemoriseGood = true,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = true,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = true,
            isLikesWorkAlone = true
        ),

        // Endustri Muhendisligi
        Department(
            id = 0,
            departmentName = "Endüstri Mühendisliği",
            isMemoriseGood = false,
            isHumanReleationsGood = true,
            isArithmeticGood = true,
            isComplexSystemGood = false,
            isInterestedMoney = true,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = true,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = true,
            isWantsDifference = false,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = false
        ),

        // Iktisat
        Department(
            id = 0,
            departmentName = "İktisat",
            isMemoriseGood = false,
            isHumanReleationsGood = false,
            isArithmeticGood = true,
            isComplexSystemGood = false,
            isInterestedMoney = true,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = true,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = true,
            isWantsDifference = false,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Ingiliz Dili ve Edebiyati
        Department(
            id = 0,
            departmentName = "İngiliz Dili ve Edebiyatı",
            isMemoriseGood = true,
            isHumanReleationsGood = false,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = true,
            isGoodTeacher = true,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = false
        ),

        // Uluslararasi İliskiler
        Department(
            id = 0,
            departmentName = "Uluslararası İlişkiler",
            isMemoriseGood = false,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = true,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = false
        ),

        // Beslenme ve Diyetetik
        Department(
            id = 0,
            departmentName = "Beslenme ve Diyetetik",
            isMemoriseGood = false,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = true,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = true,
            isLikesWorkAlone = true
        ),

        // Turk Dili ve Edebiyati
        Department(
            id = 0,
            departmentName = "Türk Dili ve Edebiyatı",
            isMemoriseGood = true,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = true,
            isGoodTeacher = true,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Veterinerlik
        Department(
            id = 0,
            departmentName = "Veterinerlik",
            isMemoriseGood = true,
            isHumanReleationsGood = false,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = true,
            isForeignLanguageEasy = false,
            isInterestedMedical = true,
            isHandleCrisis = false,
            isLikesOffice = false,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = true,
            isLikesWorkAlone = false
        ),

        // Havacilik Yonetimi
        Department(
            id = 0,
            departmentName = "Havacılık Yönetimi",
            isMemoriseGood = false,
            isHumanReleationsGood = false,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = true,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = true,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = true,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = false
        ),

        // Yonetim Bilisim Sistemleri
        Department(
            id = 0,
            departmentName = "Yönetim Bilişim Sistemleri",
            isMemoriseGood = false,
            isHumanReleationsGood = false,
            isArithmeticGood = true,
            isComplexSystemGood = true,
            isInterestedMoney = false,
            isInterestedTechDevices = true,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = true,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = true,
            isWantsDifference = true,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = true,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Uluslararasi Ticaret ve Lojistik
        Department(
            id = 0,
            departmentName = "Uluslararası Ticaret ve Lojistik",
            isMemoriseGood = false,
            isHumanReleationsGood = true,
            isArithmeticGood = true,
            isComplexSystemGood = true,
            isInterestedMoney = true,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = false,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = true,
            isWantsDifference = true,
            isEmotionalQuotientDominant = false,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = false
        ),

        // Sinif Ogretmenligi
        Department(
            id = 0,
            departmentName = "Sınıf Öğretmenliği",
            isMemoriseGood = true,
            isHumanReleationsGood = true,
            isArithmeticGood = true,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = false,
            isGoodTeacher = true,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = true,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = true,
            isLikesWorkAlone = false
        ),

        // Felsefe
        Department(
            id = 0,
            departmentName = "Felsefe",
            isMemoriseGood = true,
            isHumanReleationsGood = true,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = true,
            isGoodTeacher = false,
            isGoodListener = true,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = true,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = false,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = true
        ),

        // Sinema ve Televizyon
        Department(
            id = 0,
            departmentName = "Sinema ve Televizyon",
            isMemoriseGood = false,
            isHumanReleationsGood = false,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = true,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = false,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = true,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = false,
            isGoodAtFoods = false,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = true,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = false
        ),

        // Gastronomi ve Mutfak Sanatlari
        Department(
            id = 0,
            departmentName = "Gastronomi ve Mutfak Sanatları",
            isMemoriseGood = true,
            isHumanReleationsGood = false,
            isArithmeticGood = false,
            isComplexSystemGood = false,
            isInterestedMoney = false,
            isInterestedTechDevices = false,
            isGoodDrawer = false,
            isLikesBooksAndMovies = true,
            isGoodTeacher = false,
            isGoodListener = false,
            isInterestedCrafting = true,
            isLikesLearnBrilliantKnowledge = true,
            isHandsDontVibrate = false,
            isForeignLanguageEasy = false,
            isInterestedMedical = false,
            isHandleCrisis = false,
            isLikesOffice = false,
            isGoodAtFoods = true,
            isWantsGovermentJob = false,
            isEligibleForManager = false,
            isWantsDifference = true,
            isEmotionalQuotientDominant = true,
            isLikesProgramming = false,
            isLikesHelping = false,
            isLikesWorkAlone = false
        ),
    )
}